# Generated by Django 6.0.5 on 2026-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('application_date', models.DateField()),
                ('role_track', models.CharField(choices=[('data', 'Data'), ('backend_platform', 'Backend/Platform'), ('ml_data_science', 'ML/Data Science'), ('devops_service_ops', 'DevOps/Service Ops'), ('general_it', 'General IT'), ('other', 'Other')], max_length=40)),
                ('cover_letter_text', models.TextField()),
                ('key_claims', models.TextField(blank=True)),
                ('interview_prep_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
            ],
            options={
                'ordering': ['-application_date', 'company'],
            },
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'education entries',
                'ordering': ['-start_year', 'school'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('english', 'English'), ('french', 'French')], max_length=20)),
                ('role_track', models.CharField(choices=[('data', 'Data'), ('backend_platform', 'Backend/Platform'), ('ml_data_science', 'ML/Data Science'), ('devops_service_ops', 'DevOps/Service Ops'), ('general_it', 'General IT'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('english', 'English'), ('french', 'French')], max_length=20)),
                ('role_track', models.CharField(choices=[('data', 'Data'), ('backend_platform', 'Backend/Platform'), ('ml_data_science', 'ML/Data Science'), ('devops_service_ops', 'DevOps/Service Ops'), ('general_it', 'General IT'), ('other', 'Other')], max_length=40)),
                ('content', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
